logging:
  config: /etc/simple/logback-spring.xml


spring:
  datasource:
    url: jdbc:mysql://db.zhangyongqiao.com:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Password!&

  redis:
    host: manager.e-healthcare.net
    password: meetinglive
    port: 31379
  mqtt:
    server:
      username: admin
      password: public
      url: tcp://drone.koudaibook.com:1883
    client:
      publishId: "publish-id"
      subscribeId: "subscribe-id"
    default:
      topic: "ci/simple/center/soa-server/#"
      completionTimeout: 3000

server:
  servlet:
    context-path: /connection
simple:
  domainName: koudaibook.com

qiniu:
  accessKey: JMVsA4svqk_TUAjq9jOKy0fLVxBaJpiaAAhcn0gr
  secretKey: 39xrdVIpTa65jjPkAB9RCjzdDKN_VY4KdcPkhNjD
  bucket: windwithlife
  domainName: http://images.koudaibook.com